{% set version = "20.3" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 3c292b474fda1671ec57d46d739d072bfd495a4f51ad01a055121d81e952b7a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyparsing >=2.0.2
    - six

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache 2.0 or BSD 2-Clause
  license_file: LICENSE
  summary: Core utilities for Python packages

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
