{% set version = "20.9" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 5b327ac1320dc863dca72f4514ecc086f31186744b84a230374cc1fd776feae5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - flit
    - python
    - pip

  run:
    - python >=2.7
    - pyparsing >=2.0.2

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
