{% set version = "25.0" %}
{% set python_min = "3.8" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.3
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - packaging
  commands:
    - pip check

about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
  doc_url: https://packaging.pypa.io/
  dev_url: https://github.com/pypa/packaging

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - matthewfeickert
    - ofek
