schema_version: 1

context:
  version: "26.1"
  python_min: "3.8"

package:
  name: packaging
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/packaging/packaging-${{ version }}.tar.gz
  sha256: f042152b681c4bfac5cae2742a55e103d27ab2ec0f3d88037136b6bfe7c9c5de

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.12
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - packaging
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
  homepage: https://github.com/pypa/packaging
  repository: https://github.com/pypa/packaging
  documentation: https://packaging.pypa.io/

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - matthewfeickert
    - ofek
